sudo:required
language: generic 
services:
    - docker
    
before_install:
    - docker build -t mail2pps/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mail2pps/docker-react npm run test -- --coverage   