version: '3.2'
services:
    web:
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile.dev
        environment:
            env_file: .env
            NODE_ENV: development            
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - .:/app
    tests:
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - .:/app
        environment:
            env_file: .env
            NODE_ENV: development
        command: ["npm", "run","test"]