# Specify the base image
FROM node:alpine

WORKDIR /app/

#install some dependecis
COPY ./package.json ./
RUN npm install # --silent
COPY ./ ./

#Default command
EXPOSE 80
CMD [ "npm", "run", "start" ]